martinpitt/python-dbusmock

- tests/test_ofono.py
Ubuntu's version of the list_modems script obfuscates 'private' data.
Check for some other properties we set in the mock that aren't private
instead.
> test_ofono: Don't check "private" fields

- tests/test_bluez5.py
New messages were introduced in bluez 5.45 which confused this simplistic
test case. So rather than expecting blank, we should expect the output
to change over time. Just so long as the output doesn't list "Controller"
then it's a pass. (LP: #1696480)
> Fix failure of test_no_adapters with bluez 5.45

- tests/test_networkmanager.py
This is due to name changes in network-manager from 802-11-wireless to wifi and similar for ethernet, which causes the expected output to be different.
Closes: #37
> Fix nm tests from new change

- .travis.yml
- tests/run-ubuntu-chroot
Pull in recent changes to tests/run-ubuntu-chroot from umockdev:
- Run on Ubuntu devel series by default instead of latest stable
- Explicitly run tests on artful (latest Ubuntu stable)
- Support running tests against -proposed with setting `$PROPOSED`
- Mount /dev/pts in the build chroot
- Build and copy out the release tarball
> tests: Run on Ubuntu devel, support i386 and proposed

- dbusmock/templates/networkmanager.py
I didn't find this method in your template, but I need it to test our API to talk to NetworkManager.
> NetworkManager: add GetDeviceByIpIface method

- dbusmock/templates/logind.py
Suspend to hibernate is a new feature in systemd, merged in:
github.com/systemd/systemd/pull/8274
It was renamed to suspend then hibernate in:
https://github.com/systemd/systemd/pull/8606
> Add support for suspend-then-hibernate

- dbusmock/templates/bluez5.py
The Change make it possible to define a different blutooth class. New parameter has a default value from the old hard coded bluetooth class id, so it won't break old code.
> add PairDevice 'class_' parameter

- dbusmock/templates/networkmanager.py
NetworkManager supports the "State" and "StateReason" properties for
a long time. The "StateReason" redundantly also contains the state
value (for historic reasons).
In the past, NMClient's cache in libnm looked at the "State" property
to get the state. This is going to change (in 1.22) and libnm will consider
only at the "StateReason" for both properties. This change in libnm would
break dbusmock.
Note that NetworkManager/libnm didn't break API. The only think that is going
to change is that libnm will require that "StateReason" property is
present. The breakage is caused by dbusmock not providing a perfect stub
implementation of NetworkManager's API.
See-also: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/commit/ec39498fc6d70cf6887f08b4dfbc5cff021fc231
> NetworkManager template: add "StateReason" property to devices

- dbusmock/templates/networkmanager.py
The ID property was added to an active connection. This fix adds the possibility to get an active connection by ID.
> NetworkManager template: Add Active Connection ID

- dbusmock/templates/networkmanager.py
- tests/test_networkmanager.py
Added the `Enable` method to the `NetworkManager` object that controls overall networking. Apart from that, the corresponding property `NetworkingEnabled` is also updated.
> Handle NetworkManager NetworkingEnable property

- dbusmock/templates/networkmanager.py
[AddConnectionUnsave](https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Settings.html#gdbus-method-org-freedesktop-NetworkManager-Settings.AddConnectionUnsaved) method has been added to [org.freedesktop.NetworkManager.Settings](https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Settings.html). The method has the same signature, and the same behavior as [AddConnection](https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Settings.html#gdbus-method-org-freedesktop-NetworkManager-Settings.AddConnection) except the first one doesn't save a key-file on the disk, but for mocking, it doesn't matter. Therefore, the previously implemented `SettingsAddConnection` has been utilized.
> NetworkManager template: AddConnectionUnsaved

- dbusmock/mockobject.py
- dbusmock/templates/systemd.py
- tests/test_api.py
- tests/test_systemd.py
The templates shares a common implementation, in systemd-base.py, that
implements mocked versions of StartUnit, StartTransientUnit and
StopUnit. It imitates systemd enough to make gnome-shell happy, thinking
it managed to launch the units it asked to have launched.
> templates: Add systemd-user and systemd-system templates

- dbusmock/templates/accounts_service.py
- tests/test_accounts_service.py
template/accounts_service: add accounts service mock implementation
it allows to create fake users to be added to the accountsservice,
implementing all the service methods.
all the user properties can be simply mocked calling the adduser mock method or
during initialization via parameters.
---
Added unit tests, however I've not added the required dependency (`gir1.2-accountsservice-1.0`) because there are two issues blocking such tests: (mainly [!61](https://gitlab.freedesktop.org/accountsservice/accountsservice/-/merge_requests/65) and [!65](https://gitlab.freedesktop.org/accountsservice/accountsservice/-/merge_requests/65))
> template/accounts_service: Add accounts service mock implementation

- dbusmock/templates/power_profiles_daemon.py
- tests/run-fedora
- tests/test_power_profiles_daemon.py
My Python-fu is weak, so I couldn't figure out how to append to the `ActiveProfileHolds` property (which is supposed to be an array), or how I could reference that recently appended "hold" to a separate store for `ReleaseHold` to use.
This is the error I get when I try to use the `.append()` path:
```
ERROR:dbus.service:Unable to append (dbus.Array([{'Profile': dbus.String('power-saver'), 'Reason': dbus.String('"g-s-d mock test"'), 'ApplicationId': dbus.String('org.gnome.SettingsDaemon.Power')}], signature=dbus.Signature('(aa{sv})')),) to message with signature v: <class 'TypeError'>: string indices must be integers
Traceback (most recent call last):
File "/home/hadess/Projects/gnome-install/bin/powerprofilesctl", line 124, in get_profiles_property
profiles = proxy.Get('(ss)', …
```
> templates: Add power-profiles-daemon template

- tests/test_power_profiles_daemon.py
See https://github.com/martinpitt/python-dbusmock/pull/79#discussion_r676145708
> tests: Fix static sleep in power-profile-daemons test

- dbusmock/templates/logind.py
- tests/test_logind.py
Properly track held inhibitors, replacing the previous dummy
implementation.
Note that previously the FD represented by the passed Inhibit_fd integer
would be passed back. This was never useful though, as it is impossible
to do anything interesting by setting the FD.
> logind: Implement Inhibit and ListInhibitors

- dbusmock/testcase.py
Even with standard_system_servicedirs empty, dbus-daemon will always add
the standard search directories in order to activate services. However,
in a test environment it is unexpected that a system service might be
started.
As such, disallow all calls to StartServiceByName, preventing any such
situation.
> dbusmock: Disallow service activation on system bus

- dbusmock/templates/iio-sensors-proxy.py
- tests/run-fedora
- tests/test_iio_sensors_proxy.py
Add template to run a mock IIO Sensors Proxy, supporting accelerometers,
compasses, proximity and light sensors.
Includes unit tests, both checking the dbus interface directly and using
the monitor-sensor debug tool, if available.
This was initially part of [this mutter MR](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1233), but @hadess suggested to upstream it for usage in other components such as g-c-c.
> templates: Add IIO Sensors Proxy support

- dbusmock/templates/power_profiles_daemon.py
It's declared as an array of a{sv} in the D-Bus interface, but the lack
of annotation means that it's exported as a{ss} instead.
> power_profiles_daemon: Update signature for Profiles array

- dbusmock/mockobject.py
- tests/test_api.py
This allows changing property with array as type. It's up to the caller
to make sure the array is populated properly. Not having this results in
AttributeError: 'dbus.Array' object has no attribute 'conjugate'
when trying to update array properties.
> mockobject: Wrap dbus.types.Array as is when changing properties

- dbusmock/templates/logind.py
- tests/test_logind.py
The two commits add the `LockedHint`/`SetLockedHint()` property/method and
amend the `Lock()`/`Unlock()` methods to emit their respective signals, as
described in the interface documentation.
> logind: additions and improvements for Lock/Unlock/LockedHint

- dbusmock/mockobject.py
- tests/test_api.py
- tests/test_gnome_screensaver.py
- tests/test_upower.py
This is invaluable when debugging property changes with multiple object
paths involved, such as bluez with multiple Bluetooth adapters.
> mockobject: Print the object path when manipulating properties

- dbusmock/templates/bluez5.py
When starting a new discovery, we would send signals that the properties
were changed, but we never set those as properties internally, so anyone
fetching them would get the default value.
Modify the property values directly instead of using intermediate
variables.
> bluez: Fix stale Discoverable/Discovering property

- dbusmock/templates/bluez5.py
Export the same device properties as bluez would so they can be easily
updated by tests, eg. setting the Class or Icon.
> bluez5: Add all missing device properties

- dbusmock/templates/bluez5.py
It's Modalias, not ModAlias.
Fixes: c61d87a87bd58e7ff20f59c1366aea4746b5760e
> bluez5: Fix Modalias device property

- dbusmock/templates/bluez5.py
This is used to mock a "normal" adapter removal in bluetoothd, such as a
USB adapter being unplugged or a killswitch being activated.
Used in https://gitlab.gnome.org/GNOME/gnome-bluetooth/-/merge_requests/130
> bluez5: Add RemoveAdapterWithDevices() mock function

- dbusmock/testcase.py
- tests/test_api.py
- tests/test_code.py
We now provide a classmethod to get the service directory of the dbus
server that will be launched. Also new is the enable_service function
which will symlink the service in order to enable it in the test
environment.
---
This is working great for the g-s-d tests. The attribute is a bit ugly, but `cls` can be either `DBusTestCase` or any subclass, making it unpredictable if it is first called with a derived class as an argument. As such, the code just hardcodes `DBusTestCase` (and manually mangles the name for the delattr).
> dbusmock: Allow creating/enabling .service files

- dbusmock/mockobject.py
- dbusmock/templates/ofono.py
- tests/test_api.py
For interfaces loaded via a template, calls to static methods were never
logged and the MethodCalled signal was never emitted. Fix this by
wrapping the function from the module in what is a "standard" Python
function debug decorator, except that it adds the calls to the log
instead.
This is a bit awkward since the first argument is always self - we need
to pass that on to the function but we don't want to log it.
*Note: not 100% sure that's the right approach but couldn't think of anything else*
> Ensure method calls from templates are logged

- dbusmock/mockobject.py
If the `super()` constructor `dbus.service.Object.__init__` raises an
exception, we end up with `self.logfile` never being assigned. This causes
an AttributeError during `__del__`, obscuring the actual issues in the
code.
> Ignore a missing self.logfile on errors

- dbusmock/mockobject.py
> Convert method arguments to dbus signatures

- dbusmock/templates/ofono.py
This was fixed properly in commit 501d96249b8416.
This reverts commit e52f87e17e11285cc70752c053a9db7a2064e2d9.
> Revert "ofono template: Explicitly specify empty dict signature"

- dbusmock/templates/bluez5.py
With the more thorough signature checking from #118, the gnome-bluetooth
unit tests fail, because Pair() called PairDevice() with 2 arguments
but PairDevice() expects 3 arguments. Optional arguments with a default
are not really something that exists in the interoperable subset of
D-Bus.
Resolves: #123
> dbusmock.templates.bluez5: Don't rely on a default value for an argument

- dbusmock/testcase.py
It is expected that the name is not yet owned. And if we continue, we'll
likely try to re-initialize an existing object that should have been
cleaned up. If this happens, the likely explanation is that a previous
test left the mock environment in a bad state, so error out immediately
with an error that is easier to understand.
> testcase: Throw an error when spawning a well-known name that exists

- tests/test_code.py
For tests, we can easily run past the limit of 50 and it doesn't
necessarily indicate bad code quality.
> tests: disable the "too many statements" error in pylint

- dbusmock/mockobject.py
- tests/test_api.py
- tests/test_code.py
Sits on top of ~~#128~~ #130 
~~Requires dbus-python to update first: https://gitlab.freedesktop.org/dbus/dbus-python/-/merge_requests/13~~
Switch to use dbus-python's `SignalMessage` directly for our signal emission instead of wrapping the `@signal` decorator.
Add a new DBus method EmitSignalDetailed that also takes an a{sv} of
magic keywords for details to be passed down.
The only supported detail right now is "destination" for the destination ~~, using
the new destination_keyword from dbus-python, see
https://gitlab.freedesktop.org/dbus/dbus-python/-/merge_requests/18~~
This allows us to send signals to one specific target even if they don't
have a match rule setup (used by libportal for example).
> Allow setting the destination on signals

- setup.py
This is a direct dependency required to import dbusmock itself.  This
lets `import dbusmock` work after `pip install python-dbusmock` in a
clean venv.
Unfortunately, tests don't run yet.  Dealing with our dependency on
`gi.repository` is going to be a lot more complicated.
Fixes #133
> setup.py: list our dbus-python dependency

- .github/workflows/release.yml
- dbusmock/__init__.py
- setup.py
- tests/run-debian
- tests/test_api.py
autotools's version checks or upower's test suite rely on this, so this
is API. Add a unit test to ensure it exists.
This should ideally be generated automatically [1], but that does not
work as long as packit, rpm builds etc. don't get along with pyproject.
So for the time being, move the static version back to
dbusmock/__init__.py, and read it from setup.py instead.
[1] https://github.com/martinpitt/python-dbusmock/pull/140
----
See [0.28.2 Debian regression](https://tracker.debian.org/pkg/python-dbusmock), breaks upower. Also thanks to @benjamb for his attempt in #140!
> Bring back dbusmock.__version__, revert sdist build to setup.py

- dbusmock/templates/ofono.py
For the continued Python string, the f-string identifier has to be
re-specified again. Without this, tests of lomiri-indicator-network
breaks.
Fixes: 872a7e33 ("Move to f-strings")
> ofono template: fix conversion to f-strings

- setup.cfg
- setup.py
Commit 842d2506fb71 broke `pip install` and also some variants of
PEP-517 build tools: `.` is not in their default `sys.path` any more.
Merely adding that to the search path is not sufficient: building an
sdist in a venv is tripping over the missing `import dbus`, as
dbus-python is just a runtime dependency, not a build-time one.
So instead of importing `dbusmock.__version__` in setup.py, ask
setuptools to dynamically generate the version in a declarative way, in
setup.cfg.
Many thanks to Michał Górny for analyzing this and proposing this
solution!
Fixes #142
> setup.py: Fix ModuleNotFoundError

- .flake8
- .github/workflows/tests.yml
- .gitignore
- MANIFEST.in
- dbusmock/__init__.py
- dbusmock/mockobject.py
- packit.yaml
- pyproject.toml
- tests/run
- tests/run-debian
- tests/run-fedora
- tests/test_api.py
- tests/test_code.py
Determine dbusmock.__version__ from package metadata instead of
hardcoding it. With that, the release process is simply "push a signed
tag".
Drop MANIFEST.in. setuptools-scm automatically includes all git-tracked
files into the tarball.
See https://github.com/pypa/setuptools_scm
> Use setuptools_scm to determine version

- dbusmock/mockobject.py
- tests/test_api.py
While we can easily `mock.AddObject()` an object with a different path,
sending a signal from that object is more complicated. And even there it
doesn't cover the case where we want to fake a signal from an object
created by someone else.
So, let's fix this by adding a path argument to EmitSignalDetailed.
> mockobject: allow sending signals from a specific path

- dbusmock/templates/bluez5-obex.py
The OBEX tests in folks fail with:
(/build/folks/src/build/tests/bluez/bluez-individual-retrieval:3488):
folks-WARNING **: 17:30:47.981:
Error preparing persona store ‘bluez:00:00:00:00:00:00’:
The OBEX address book transfer from device ‘My Phone’ failed:
GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs:
Invalid arguments: Expected a string or unicode object
`PullAll` passes a `pathlib.Path` to `manager.EmitSignal`. Converting it to a `str` fixes the issue.
> Fix OBEX PullAll after pathlib conversion

- dbusmock/templates/power_profiles_daemon.py
It should be an 'as' (array of strings), not an 'a(as)' (array of tuples containing an array of strings) which it is now.
For reference:
https://gitlab.freedesktop.org/hadess/power-profiles-daemon/-/blob/0.12/src/net.hadess.PowerProfiles.xml#L127
> templates/power_profiles: Fix Actions property type

- README.md
- dbusmock/mockobject.py
- tests/test_api.py
This is useful for shipping templates in distro -devel packages which
are not generic or stable enough to be maintained in the dbusmock
project.
Fixes #168
----
[rendered documentation](https://github.com/martinpitt/python-dbusmock/tree/xdg-templates#templates)
> Support loading templates from XDG_DATA_DIRS

- dbusmock/testcase.py
- tests/test_api.py
dbusmock may leave dbus-daemon zombie processes because nothing is
waiting for them, so use waitpid() to ensure we don't end up in such
state
/cc @jadahl
> testcase: Wait for PID after killing it

- tests/run-fedora
The root cause for this got fixed in glib 2.77.1:
https://gitlab.gnome.org/GNOME/glib/-/issues/3054
This reverts commit 0b4c5d9b858a54aacd87dc7b1138cc3742947768.
Fixes #177
> Revert "test: Drop power-profiles-daemon from Rawhide"

- README.md
- dbusmock/__main__.py
- tests/test_cli.py
It may be used to quickly debug interfaces
Allowing to use something like `python3 -m dbusmock -t upower -c d-feet`
> cli: Add support for running custom commands or shell on the mock environment

- README.md
- dbusmock/pytest_fixtures.py
- packaging/python-dbusmock.spec
- tests/conftest.py
- tests/run-debian
- tests/run-fedora
- tests/test_api_pytest.py
Add a new dbusmock.pytest_fixtures module which exports an initial set of fixtures. These mostly just wrap DbusTestCase into a fixture, plus some convenience functions for starting a system or session bus. In the future we may have more fixtures to spawn templates, etc.
Ensure that all of our unit tests run with pytest. As that is expensive, only run it for TEST_CODE=1 in Fedora stable. On the others, only run the basic TestAPI checks and the fixtures checks.
This was co-developed with Peter Hutterer @whot, thank you!
---
I took some inspiration from https://gitlab.freedesktop.org/libinput/libei/-/merge_requests/243 and https://github.com/flatpak/xdg-desktop-portal/pull/1062
> Add initial pytest support

- dbusmock/testcase.py
No need to try to os.kill() that same pid if it no longer exists. Worst case we may end up killing an unrelated process.
> If we don't have a child to wait for, stop

- .github/workflows/pages.yml
- .gitignore
- dbusmock/mockobject.py
- doc/conf.py
- doc/index.rst
For reference, this is how it looks like: https://whot.github.io/python-dbusmock/
Needs enabling in https://github.com/martinpitt/python-dbusmock/settings/pages, change to `Source: Github Action`.
This is the minimal conversion only, using the readme as index page and with a few rst-ifications in the `DBusMockObject` class (but not in `DBusTestCase` because that would conflict with #184). Once it's in place we can prettify all this one-by-one.
~~A helper `Makefile` is included too to build it locally.~~
> doc: hook up sphinx

- tests/run
- tests/run-debian
- tests/run-fedora
- tests/test_code.py
unittest and pytest may pass locally only to fail with
near-indecipherable logs in the CI - caused by TEST_CODE being set which
triggers the pylint, ruff and mypy checks.
Let's invert that check so local checks will run these by default unless
explicitly disabled and the CI disables it in the specific test runs.
> Default to running static tests

- dbusmock/__init__.py
- dbusmock/pytest_fixtures.py
- dbusmock/testcase.py
- tests/test_api_pytest.py
Filing as draft for now because the last commit *may* break backwards compat, see below.
I noticed that my dbus-daemons didn't get terminated when using dbusmock in the xdg-desktop-portal which led to a bit of a rabbit hole. So I figured "let's fix this properly" :smile: 
For (understandable) historical reasons, the `DBusTestCase` class handled everything as `@classmethod`. That causes a few issues though because the `cls` argument is mostly the real class but in some cases it's `DBusTestCase`. This can lead to a getter resolving to`DBusTestCase.somevar` but the setter resolving to `MyTestClass(DBusTestCase).somevar`.
The first few patches disentangle that to make sure we're always on the correct class instead of oscillating between `DBusTestCase` and the test class.
The last (and most …
> Fix inheritance issues and separate the mocked dbus into an object

- .pre-commit-config.yaml
- packit.yaml
A little (optional) helper to avoid screwups. After `pre-commit install` once every `git commit` then runs black and ruff and a bunch of general helpers that looked useful.
Possibly controversial: prevents direct commits to `main`, easy to drop (or work around with `git commit --no-verify` if need be).
> Add pre-commit rules

- README.md
Some of the documentation should probably move there altogether but for now let's at least have a link to it.
> README: add a link to the github pages docs

- dbusmock/templates/bluez5.py
- tests/test_bluez5.py
Over the years, this template has accumulated some hacks and bad API which made PairDevice()'s handling of the Modalias/Class/Icon properties buggy and hard to understand:
* These are *static* device properties, they are not supposed to change during pairing.
* Commit ee29a4403359b6a added these as some kind of "dynamic fallback default" when they were not initialized by the caller after AddDevice().
* Commit 59d6af0dca3e silently broke that fallback default by changing AddDevice() to set these device properties to empty strings.
* Commit fae4be7f49c0861 added another really bad API for setting Class in PairDevice()(). That API didn't fit into D-Bus (see commit 8968284e8b which had to make it a non-default parameter) and also broke the API, and moreover it is totally unintuitive -- the …
> bluez5: Clean up static default properties, re-drop PairDevice class_ parameter

- dbusmock/templates/bluez5.py
The third (device class) argument to PairDevice was removed in 0.30.1, but this call to it was still passing a third parameter, resulting in an error from dbus-python whenever Pair() was called. This caused a unit test regression in gnome-bluetooth.
Fixes: 63264e18 "bluez5: Clean up static default properties, re-drop PairDevice class_ parameter"  
Resolves: https://github.com/martinpitt/python-dbusmock/issues/193  
Bug-Debian: https://bugs.debian.org/1057564
> bluez5: Fix invalid arguments to PairDevice

- dbusmock/templates/power_profiles_daemon.py
- pyproject.toml
- tests/run-debian
Version 0.20 moved to D-Bus name `org.freedesktop.UPower.PowerProfiles`, and corresponding changes to the object path/interface: https://gitlab.freedesktop.org/upower/power-profiles-daemon/-/releases/0.20
The real daemon also still listens to the old name, but we can't do that in dbusmock: BUS_NAME and friends cannot be parameterized, as their loading and instantiation happens before calling the `load()` function.
`powerprofilesctl` now only looks at the new name, so we need to adjust the template. The new version is in Fedora 39 to rawhide and also in Debian testing, so for ongoing development it's more useful to present the current API.
---
See [recent test failures](https://github.com/martinpitt/python-dbusmock/actions/runs/8014608956)
> power_profiles_daemon: Move to org.freedesktop.UPower.PowerProfiles

- dbusmock/templates/power_profiles_daemon.py
- dbusmock/templates/upower_power_profiles_daemon.py
- tests/run-debian
- tests/test_power_profiles_daemon.py
This works like the existing power_profiles_daemon template, but for the
new D-Bus name/object path introduced in
https://gitlab.freedesktop.org/upower/power-profiles-daemon/-/releases/0.20
Enable integration test on Ubuntu, which has version 0.13 in 22.04 LTS.
> Add upower_power_profiles_daemon template

- tests/test_power_profiles_daemon.py
https://gitlab.freedesktop.org/upower/power-profiles-daemon/-/merge_requests/167 will change the output of `powerprofilesctl version`. Take the first version number from the ouput instead of assuming that the output starts with it.
---
@superm1 FYI
> test: Robustify powerprofilesctl version parsing

- dbusmock/__main__.py
- dbusmock/templates/gnome_screensaver.py
That doesn't like the `# fmt off` annotations:
> RUF028 This suppression comment is invalid because it cannot be in an expression, pattern, argument list, or other non-statement
So throw beauty out of the door and concede to the battling tools.
---
Fixes [recent nightly unit test run](https://github.com/martinpitt/python-dbusmock/actions/runs/8106463065/job/22156433476)
> Adjust to ruff 0.3.0

- dbusmock/__main__.py
libglib, when installed on macOS, has the file extension `.dynlib`.
> Corrected loading of libglib on macOS

- .github/workflows/tests.yml
- packit.yaml
> test: Drop CentOS 8, add CentOS 10

- dbusmock/templates/bluez5.py
- tests/test_bluez5.py
Basic implementation of the `org.bluez.LEAdvertisingManager1` and `org.bluez.AdvertisementMonitorManager1` interfaces on mock adapters.
Fixes #20
> bluez5: Implement Advertising APIs

- dbusmock/templates/bluez5.py
- tests/test_bluez5.py
While I'm in there..
I noticed during some further testing that when starting `bluetoothctl` multiple times, with the bluez5 mock active,  an `AttributeError` is raised instead of the expected `org.bluez.Error.AlreadyExists`:
```sh
$ systemctl mask bluetooth
$ systemctl stop bluetooth
$ python3 -m dbusmock --system -t bluez5 -e $SHELL
$ bluetoothctl
Waiting to connect to bluetoothd...
1720009617.228 RegisterAgent "/org/bluez/agent" ""
[SIGNAL] org.freedesktop.DBus.Mock.MethodCalled
[bluetooth]# Agent registered
[bluetooth]# quit
$ bluetoothctl
Waiting to connect to bluetoothd...
1720009619.963 RegisterAgent "/org/bluez/agent" ""
1720009619.963 RegisterAgent raised: 'DBusMockObject' object has no attribute 'agent_path'
[SIGNAL] org.freedesktop.DBus.Mock.MethodCalled
[bluetooth]# Failed to …
```
> bluez5: Fix AttributeError when registering an agent twice

- tests/test_iio_sensors_proxy.py
- tests/test_modemmanager.py
Two files tried to documen what is being tested and got it wrong.  Drop that duplicate informtion as it's obvious from the class names.
> tests: Drop outdated doc strings

- packit.yaml
- pyproject.toml
- tests/main.fmf
> Various fixes

- dbusmock/mockobject.py
- pyproject.toml
- tests/test_api.py
This allows to create objects instanciated from a DBusMockObject subclass in mock templates. That way, implementing dynamic objects becomes easier by using dbus decorators:
```python
class ColordDevice(mockobject.DBusMockObject):
@dbus.service.method(DEVICE_IFACE, in_signature='', out_signature='i')
def Test(self):
return 42
self.add_object(ColordDevice, device_path, DEVICE_IFACE, {}, [])
```
> mockobject: Allow adding objects derived from DBusMockObject

- dbusmock/__init__.py
- dbusmock/__main__.py
- dbusmock/mockobject.py
- dbusmock/testcase.py
- pyproject.toml
- tests/test_api_pytest.py
- tests/test_cli.py
- tests/test_logind.py
- tests/test_networkmanager.py
- tests/test_notification_daemon.py
- tests/test_ofono.py
- tests/test_power_profiles_daemon.py
- tests/test_timedated.py
- tests/test_upower.py
According to https://endoflife.date/python python 3.7 has been EOSed 27 Jun 2023.
Filter all code over `pyupgracde --py38-plus`.
> drop python<=3.7 support

- tests/test_bluez5.py
This file doesn't exist in the Nix build sandbox.
Fixes: 812dc61 ("tests: Skip bluez test_advertise on RHEL 10")
> tests: fix bluez test when no /etc/os-release

- tests/test_bluez5.py
[It is probably a Glibc bug that sscanf as used by bluez accepts 0x01 for this value.][1]  For portability, use the unprefixed hex value. Based on bluez's own [documentation][2], I don't think the 0x is required.
[1]: https://www.openwall.com/lists/libc-coord/2024/10/15/2
[2]: https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/client/bluetoothctl-monitor.rst?id=3d9900eb754d277ef6abf21bed827cdc9e79ddb4
> tests: fix test_monitor on musl

- dbusmock/templates/gsd_rfkill.py
- tests/test_gsd_rfkill.py
This can be useful to test behavior of dependent components like desktop shells.
Single properties can be toggled via
```
gdbus call --session -d org.gnome.SettingsDaemon.Rfkill -o /org/gnome/SettingsDaemon/Rfkill -m org.freedesktop.DBus.Properties.Set 'org.gnome.SettingsDaemon.Rfkill' 'BluetoothHasAirplaneMode' "<true>"
```
and airplane mode for all wwan/bt/wifi at once:
```
gdbus call --session -d org.gnome.SettingsDaemon.Rfkill -o /org/gnome/SettingsDaemon/Rfkill -m org.freedesktop.DBus.Mock.SetAirplaneMode true
```
I can see that this might be to DE specific but I thought I'd submit it as it might be useful to others.
> Add gsd-rfkill mock

- dbusmock/templates/modemmanager.py
- tests/test_modemmanager.py
Doing userspace development for cell broadcast messages can be tricky as they're very rare in the wild. If one doesn't mock ModemManager one needs to have a small GSM cell for testing.
Hence add a `AddCbm()` message to add cell broadcast messages to the MM mock.
```
mm_server.obj.AddCbm(2, 4383, "This is a test)
```
Messages can be deleted via MMs API:
```
busctl call --system org.freedesktop.ModemManager1 /org/freedesktop/ModemManager1/Modems/8 org.freedesktop.ModemManager1.Modem.CellBroadcast Delete o /org/freedesktop/ModemManager1/Cbm/5
```
and listed via MMs API:
```
busctl call --system org.freedesktop.ModemManager1 /org/freedesktop/ModemManager1/Modems/8 org.freedesktop.ModemManager1.Modem.CellBroadcast List
```
This functionality is not yet in a released MM version (but merged into …
> modemmanager: Allow to add Cell broadcast messages

- packaging/python-dbusmock.spec
Should fix [failed packit propose-downstream](https://dashboard.packit.dev/jobs/propose-downstream/13307)
> spec: Adjust Source URL to PEP-625 tarball name

- packit.yaml
Drop the redundant targets which are already implicitly triggered by the "tests" job.
> packit: Test builds on other architectures

- dbusmock/templates/modemmanager.py
- tests/test_modemmanager.py
The channel setting API is not yet in a released version of ModemManager so I didn't add a `mmcli` test.
> modemmanager: Add operator ID and allow to set channels

- dbusmock/mockobject.py
- tests/test_api.py
Updating a Struct or Dict property fails because they have no conjugate method. We don't need to wrap them, so they really behave like Array, so let's just treat them in the same way.
> mockobject: Fix _wrap_in_dbus_variant for Struct and Dict types

- tests/run-fedora
The template has broken logic, and does not work any more with iio-sensor-proxy 3.7. See https://github.com/martinpitt/python-dbusmock/issues/241
> test: Drop iio-sensor-proxy tests on Fedora

- distro/python-dbusmock.spec
Drop unused BuildRequires on python3dist(wheel)
See https://github.com/fedora-eln/eln/issues/284
---
By way of https://src.fedoraproject.org/rpms/python-dbusmock from @hroncok , thanks!
> Drop redundant manual BuildRequires

- dbusmock/testcase.py
- tests/test_api.py
With the previous polling loop there was a short window where the socket
existed, but dbus-daemon didn't listen to it yet. Fix this by using
`--print-pid` and waiting for the result. dbus-daemon guarantees that
this will only be printed after it is ready to accept connections.
Thanks to Simon McVittie for finding this and proposing the solution!
(Ironically, the dead code removed in the previous commit did it right.
But avoid forking here.)
https://bugs.debian.org/1109272
---
Thanks @smcv !
> Fix dbus-daemon startup race condition

- dbusmock/templates/systemd.py
- tests/test_notification_daemon.py
Ubuntu 25.10 introduces an AppArmor profile for notify-send, which only allows it to talk to the real daemon.
https://launchpad.net/bugs/2121092
> test: Skip test_notification_daemon with AppArmor profile
